[features]
seeds = false
skip-lint = false

[programs.localnet]
oracle = "9UYoqKcSHFhTBRoiYBcrkabsBbUKAdx68TZGLKokZKR1"
consumer = "4aFLyxNC94mvefKLXDZ7eBbMVe367nZXW5txec8kX6JW"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
